### ISSUE TITLE
About power_control ForceRestart

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Usecase-Checkers#57] opened 2021-12-28 06:39 UTC
Hi,
When I sent power control command:
python3 power_control.py -r 192.168.0.116 -u <username> -p <password> -S Always

>>Found 1 system instances
Resetting Self using ForceOff
Task is Done!
Monitoring power state for Self...
Resetting Self using ForceRestart
Monitoring power state for Self...
ERROR: Self was not in the On state after using ForceRestart as the reset type.
Resetting Self using GracefulShutdown
Monitoring power state for Self...
Resetting Self using On
Task is Done!
Monitoring power state for Self...

I refer the schema ComputerSystem.v1_15_0.json mention "The ForceRestart value shall perform a ForceOff action, followed by an On action.". And refer an example in Specification: 
![Usecase_power_forcerestart](https://user-images.githubusercontent.com/85208691/147534975-724ade55-524e-4643-8d2c-526167a7e2fd.JPG)

So I think whether the ForceRestart should not be after ForceOff then avoid show Error message.

Thanks.

**Comment by mraineri** [comment] 2022-01-04 13:55
The expectation is that the service should perform whatever is necessary to get the system in the end result state. So, in the example you highlighted, since the system was already On, this is a no-operation.

Specifically for what you're encountering, since the system is already powered off, the expectation is the end result of a forced restart would be to bring the system back online. We have this behavior in the long description for ForceRestart:
> This value shall indicate the resource will transition to a power on state, after transiting through a restart. The transition will start immediately.

So, even if the system is off, we'd still expect some sort of restart to happen with the system in the "On" state by the end of the operation.

**Comment by FelixD999** [comment] 2022-01-05 08:33
Thanks for your answer.
But "The ForceRestart value shall perform a ForceOff action, followed by an On action."
So I guess ERROR message show "Self was not in the On state after using ForceRestart as the reset type." ascribe to it need ForceOff action again and block ForceRestart to run.
So, maybe whether add On action before ForceRestart action will run more reasonably?

**Comment by FelixD999** [comment] 2022-01-05 08:40
Thanks for your answer.
But "The ForceRestart value shall perform a ForceOff action, followed by an On action."
So I guess ERROR message show "Self was not in the On state after using ForceRestart as the reset type." ascribe to it need ForceOff action again so block ForceRestart to run.
So, maybe whether add On action before ForceRestart action will run more reasonably?

**Comment by mraineri** [comment] 2022-01-05 18:25
The problem is we see simple reset scripts that want to just cycle through all systems and perform the same action; they're going to blindly perform a single reset against all systems without doing state checks first.

ForceRestart doesn't need to internally perform a ForceOff prior to bringing the system online; if it's already off, it just needs to turn it on.

**Comment by mraineri** [comment] 2023-02-16 14:37
Closing; based on the details seen, the tool is calling out undesirable behavior based on guidance from the Redfish Forum.

**Closed by mraineri** 2023-02-16 14:37 UTC
